import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Fullstack Developer',
    company: 'RIKKEISOFT',
    logo: '/images/careers/rikkeisoft.png',
    location: 'Danang, Vietnam 🇻🇳',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2024-05',
    end_date: null,
    industry: 'Software Development',
    link: 'https://rikkeisoft.com/',
    responsibilities: [
      'Authored Basic Design Documents (BDD) and Detailed Design Documents (DDD) based on requirements provided by business analysts.',
      'Designed and developed frontend UI workflows using Vue.js 3, TypeScript, HTML5, CSS3, and Bootstrap.',
      'Built scalable backend services using Java 21 and Spring Boot with RESTful APIs, JWT authentication, Spring Security, and Redis.',
      'Integrated AWS services including SES for HTML email, SNS for SMS notifications, and CloudWatch Agent for log aggregation.',
      'Engineered a notification workflow system adaptable by module and user action.',
      'Designed and implemented a multi-level RBAC (Role-Based Access Control) system controlling page access, UI element visibility, and query permissions.',
      'Developed critical modules such as Order Management, Shipping, Statistical Reports, User Workflow, and Role Management.',
      'Built batch processing systems with AWS Lambda, scheduled via EventBridge.',
      'Wrote and maintained unit and integration tests to ensure system stability and quality.',
    ],
    isShow: true,
  },
  {
    position: 'Fullstack Developer',
    company: 'FREELANCER',
    logo: '/images/careers/freelancer.png',
    location: 'Remote',
    location_type: 'Remote',
    type: 'Freelance',
    start_date: '2024-02',
    end_date: '2024-05',
    industry: 'Web Development',
    link: null,
    responsibilities: [
      'Development web-application',
      'Teamsize: 2 people',
      'Technology: Html, Css, Reactjs, Java, Spring boot, Spring security, Maven, Docker, Git',
    ],
    isShow: true,
  },
  {
    position: 'Junior Java Developer',
    company: 'BKIT SOLUTION',
    logo: '/images/careers/bkit-solution.png',
    location: 'Danang, Vietnam 🇻🇳',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2021-10',
    end_date: '2022-06',
    industry: 'Banking Software',
    link: null,
    responsibilities: [
      'Development API for services bank',
      'Teamsize: 30 people',
      'Technology used: Git, Maven, Java 11, Sql Server, Junit, Mockito, Spring, Spring boot, Microservice, Docker, RabitMq',
    ],
    isShow: true,
  },
  {
    position: 'Fresher Java Developer',
    company: 'FPT SOFTWARE',
    logo: '/images/careers/fpt-software.png',
    location: 'Danang, Vietnam 🇻🇳',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2020-11',
    end_date: '2021-10',
    industry: 'Software Development',
    link: 'https://fptsoftware.com/',
    responsibilities: [
      'Migrate version project: Analysis different between old-new versions, learn business logic, support new members',
      'CP test: Test Ajax, Upload-Download functionality',
      'Upgrade source code: Research range of affect, SQL optimization in migrate source database',
      'Work on Jira, Git, SVN with Java, Oracle, PL/SQL, internal framework, Struts',
      'Project participation: Upgrade Tomcat 6→8, Java 6→8, Oracle 10g→19c',
      'API project: Development API backend follow requirement using Struts, Internal framework, Java, SQL server',
      'Three times the best employee of the month',
      'Top 10 RBR(Algorithm solving contest) in R-Fsoft',
      'Top 2 team hackathon in R-Fsoft with 20 teams',
    ],
    isShow: true,
  },
  {
    position: 'Intern Java Developer',
    company: 'FPT SOFTWARE',
    logo: '/images/careers/fpt-software.png',
    location: 'Danang, Vietnam 🇻🇳',
    location_type: 'Onsite',
    type: 'Internship',
    start_date: '2020-06',
    end_date: '2020-11',
    industry: 'Software Development',
    link: 'https://fptsoftware.com/',
    responsibilities: [
      'Learning Java language in fresher academy',
      'Language used: java, html, css, bootstrap, javascript, spring, spring mvc, spring boot, mysql, sql server',
    ],
    isShow: true,
  },
  {
    position: 'Backend Developer',
    company: 'KHIET LONG COMPANY',
    logo: '/images/careers/khiet-long.png',
    location: 'Danang, Vietnam 🇻🇳',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2018-12',
    end_date: '2019-07',
    industry: 'Web Development',
    link: null,
    responsibilities: [
      'Development fullstack follow required of customer',
      'Teamsize: 2-3 people',
      'Technology used: Php, js, mysql, internal framework',
      'Project participation: sdtech, training manager, survey',
    ],
    isShow: true,
  },
];
